import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          PuPesananBerhasil(),
        ]),
      ),
    );
  }
}

class PuPesananBerhasil extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(35),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 81,
                top: 474,
                child: Text(
                  'Pesanan Berhasil',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 32,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 120,
                top: 515,
                child: Text(
                  'Terimakasih pesanan \nsegera di proses',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 20,
                    fontStyle: FontStyle.italic,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 859,
                child: Container(
                  width: 355,
                  height: 45,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF5CC9E),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(35),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 866,
                child: Container(
                  width: 42,
                  height: 31,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/42x31"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 147,
                top: 866,
                child: Container(
                  width: 41,
                  height: 31,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/41x31"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 241,
                top: 866,
                child: Container(
                  width: 42,
                  height: 32,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/42x32"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 329,
                top: 866,
                child: Container(
                  width: 42,
                  height: 32,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/42x32"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 10,
                child: SizedBox(
                  width: 29,
                  height: 19,
                  child: Text(
                    '20.11',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 10,
                child: Container(
                  width: 37,
                  height: 19,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 409.14,
                top: 11,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 19,
                  height: 20.36,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/19x20"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 387,
                top: 7,
                child: Container(
                  width: 24,
                  height: 24,
                  decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 364.36,
                top: 11,
                child: Container(
                  width: 16.29,
                  height: 16.29,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/16x16"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 363,
                top: 10,
                child: Container(
                  width: 20,
                  height: 20,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 342,
                top: 12,
                child: Container(
                  width: 14,
                  height: 15,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/14x15"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 335,
                top: 8,
                child: Container(
                  width: 24,
                  height: 21,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 147,
                top: 291,
                child: Container(
                  width: 143,
                  height: 143,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/143x143"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}