import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          PaMenuSnack(),
        ]),
      ),
    );
  }
}

class PaMenuSnack extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 979,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF8A4607),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(35),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 234,
                top: 132,
                child: Container(
                  width: 162,
                  height: 183,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 357,
                top: 278,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE58A37),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 363,
                top: 278,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 357,
                top: 278,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 363,
                top: 278,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 253,
                child: Text(
                  'Gelato Matcha',
                  style: TextStyle(
                    color: const Color(0xFFD4741B),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 267,
                child: Text(
                  'IDR 17.000',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 291,
                child: Text(
                  'Tersedia',
                  style: TextStyle(
                    color: const Color(0xFF767070),
                    fontSize: 7,
                    fontFamily: 'Instrument Sans',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 238,
                top: 137,
                child: Container(
                  width: 154,
                  height: 109,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/154x109"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 331,
                child: Container(
                  width: 162,
                  height: 183,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 38,
                top: 336,
                child: Container(
                  width: 152,
                  height: 103,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/152x103"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 452,
                child: Text(
                  'Baked Potato',
                  style: TextStyle(
                    color: const Color(0xFFD4741B),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 466,
                child: Text(
                  'IDR 14.000',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 492,
                child: Text(
                  'Tersedia',
                  style: TextStyle(
                    color: const Color(0xFF767070),
                    fontSize: 7,
                    fontFamily: 'Instrument Sans',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 156,
                top: 477,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 162,
                top: 477,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 234,
                top: 331,
                child: Container(
                  width: 162,
                  height: 183,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 452,
                child: Text(
                  'Risol Mayos',
                  style: TextStyle(
                    color: const Color(0xFFD4741B),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 466,
                child: Text(
                  'IDR 10.000',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 490,
                child: Text(
                  'Tersedia',
                  style: TextStyle(
                    color: const Color(0xFF767070),
                    fontSize: 7,
                    fontFamily: 'Instrument Sans',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 239,
                top: 337,
                child: Container(
                  width: 154,
                  height: 102,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/154x102"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 355,
                top: 479,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 361,
                top: 479,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 530,
                child: Container(
                  width: 162,
                  height: 183,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 535,
                child: Container(
                  width: 154,
                  height: 105,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/154x105"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 651,
                child: Text(
                  'Gelato',
                  style: TextStyle(
                    color: const Color(0xFFD4741B),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 665,
                child: Text(
                  'IDR 15.000',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 156,
                top: 678,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 162,
                top: 678,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 691,
                child: Text(
                  'Tersedia',
                  style: TextStyle(
                    color: const Color(0xFF767070),
                    fontSize: 7,
                    fontFamily: 'Instrument Sans',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 234,
                top: 530,
                child: Container(
                  width: 162,
                  height: 183,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 651,
                child: Text(
                  'Roti Panggang Sosis',
                  style: TextStyle(
                    color: const Color(0xFFD4741B),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 665,
                child: Text(
                  'IDR 10.000',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 689,
                child: Text(
                  'Tersedia',
                  style: TextStyle(
                    color: const Color(0xFF767070),
                    fontSize: 7,
                    fontFamily: 'Instrument Sans',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 355,
                top: 678,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 361,
                top: 678,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 239,
                top: 535,
                child: Container(
                  width: 152,
                  height: 105,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/152x105"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 234,
                top: 726,
                child: Container(
                  width: 162,
                  height: 183,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 847,
                child: Text(
                  'IceCream Oreo x Taro',
                  style: TextStyle(
                    color: const Color(0xFFD4741B),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 355,
                top: 874,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 361,
                top: 874,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 861,
                child: Text(
                  'IDR 15.000',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 885,
                child: Text(
                  'Tersedia',
                  style: TextStyle(
                    color: const Color(0xFF767070),
                    fontSize: 7,
                    fontFamily: 'Instrument Sans',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 240,
                top: 731,
                child: Container(
                  width: 150,
                  height: 108,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/150x108"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 726,
                child: Container(
                  width: 162,
                  height: 183,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 731,
                child: Container(
                  width: 154,
                  height: 109,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/154x109"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 844,
                child: Text(
                  'IceCream Chocolate\nMix Vanila',
                  style: TextStyle(
                    color: const Color(0xFFD4741B),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 868,
                child: Text(
                  'IDR 15.000',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 887,
                child: Text(
                  'Tersedia',
                  style: TextStyle(
                    color: const Color(0xFF767070),
                    fontSize: 7,
                    fontFamily: 'Instrument Sans',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 156,
                top: 874,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 162,
                top: 874,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 132,
                child: Container(
                  width: 162,
                  height: 183,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 137,
                child: Container(
                  width: 154,
                  height: 109,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/154x109"),
                      fit: BoxFit.fill,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 253,
                child: Text(
                  'Sosis',
                  style: TextStyle(
                    color: const Color(0xFFD4741B),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 267,
                child: Text(
                  'IDR  10.000',
                  style: TextStyle(
                    color: const Color(0xFF8A4607),
                    fontSize: 10,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 293,
                child: Text(
                  'Tersedia',
                  style: TextStyle(
                    color: const Color(0xFF767070),
                    fontSize: 7,
                    fontFamily: 'Instrument Sans',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 156,
                top: 278,
                child: Container(
                  width: 26,
                  height: 26,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 2,
                        offset: Offset(0, 1),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 162,
                top: 278,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 925,
                child: Container(
                  width: 355,
                  height: 45,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF5CC9E),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(35),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 932,
                child: Container(
                  width: 42,
                  height: 31,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/42x31"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 145,
                top: 932,
                child: Container(
                  width: 41,
                  height: 31,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/41x31"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 239,
                top: 932,
                child: Container(
                  width: 42,
                  height: 32,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/42x32"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 327,
                top: 932,
                child: Container(
                  width: 42,
                  height: 32,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/42x32"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 87,
                top: 40,
                child: Text(
                  'Snack',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 328,
                top: 42,
                child: Text(
                  'Tambah',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 12,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 308,
                top: 37,
                child: Text(
                  '+',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Geologica',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 41,
                top: 40,
                child: Container(
                  width: 29,
                  height: 26,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/29x26"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 76,
                child: Container(
                  width: 368,
                  height: 29,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF8A4607),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFFFFCFC),
                      ),
                      borderRadius: BorderRadius.circular(35),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 81.18,
                top: 81.18,
                child: SizedBox(
                  width: 186.56,
                  height: 17.61,
                  child: Text(
                    'Cari Menu....',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 82,
                child: Container(
                  width: 21,
                  height: 18,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/21x18"),
                      fit: BoxFit.contain,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 9,
                child: SizedBox(
                  width: 29,
                  height: 19,
                  child: Text(
                    '20.11',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 13,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 18,
                top: 9,
                child: Container(
                  width: 37,
                  height: 19,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 408.14,
                top: 10,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 19,
                  height: 20.36,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/19x20"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 386,
                top: 6,
                child: Container(
                  width: 24,
                  height: 24,
                  decoration: BoxDecoration(color: const Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 363.36,
                top: 10,
                child: Container(
                  width: 16.29,
                  height: 16.29,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/16x16"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 362,
                top: 9,
                child: Container(
                  width: 20,
                  height: 20,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 341,
                top: 11,
                child: Container(
                  width: 14,
                  height: 15,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/14x15"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 334,
                top: 7,
                child: Container(
                  width: 24,
                  height: 21,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}